### ISSUE TITLE
GitHub Action to convert M4A files to MP3

### ISSUE THREAD

**Issue by MarwanRefaat** [MarwanRefaat/transcend#6]
# General goal: 
Standardize sound file formats to be MP3 files whenever they are not (the exception to this is .wav and midi files as they are higher quality and the preferred format for sound engineers)

## Considerations

-  It might make sense to create a copy and convert that rather than override the original file to preserve the highest quality original

## Work in Progress
[M4A to MP3 GitHub Action](https://github.com/MarwanRefaat/transcend/actions/workflows/m4a-to-mp3.yml)

## Resources
[This GitHub repo](https://github.com/FFmpeg/FFmpeg) has tooling for file conversion and looks promising

## Code Sample (generated with GPT-3)
Prompt:
```
Create a GitHub action that converts M4A files to MP3
```

Response:
```
# This action will convert M4A files to MP3 using the ffmpeg tool.

- name: Convert M4A to MP3
  uses: jakejarvis/ffmpeg-action@master
  with:
    args: -i input.m4a -codec:a libmp3lame -qscale:a 2 output.mp3
```

## Optional additional enhancements
![audio-file-formats](https://user-images.githubusercontent.com/24831146/179896565-f07bf2b8-1340-4cc9-991f-eb84a961b31f.png)
- [ ] Take into account the "hierarchy" of sound file types and convert (or don't convert) each accordingly
- [ ] Convert between MacOS (.aif) and Windows (.wav) file types and nest them in a respective folder per operating system
